language: objective-c
osx_image: xcode9.4
xcode_project: Powerup.xcodeproj
xcode_scheme: Powerup
xcode_sdk: iphonesimulator11.4
script: xcodebuild -project Powerup.xcodeproj -scheme Powerup -sdk iphonesimulator11.4 -destination 'platform=iOS Simulator,OS=10.3,name=iPhone 6'  -configuration Debug build test
